#!/usr/bin/env node
// @ts-check

(async () => {

    const nexe = require('nexe')
    const path = require('path')
    const rimraf = require('rimraf')

    rimraf.sync(path.resolve(__dirname, 'dist'))
    
    const output = path.resolve(__dirname, 'dist/theia')
    await nexe.compile({
        output,
        input: path.resolve(__dirname, 'src-gen/backend/main.js'),
        loglevel: process.argv.indexOf('--debug') !== -1 ? 'verbose' : 'info',
        resources: [
            'lib/**/*', // The frontend application.
            'node_modules/drivelist/build/Release/drivelist.node',
            'node_modules/find-git-repositories/build/Release/findGitRepos.node',
            'node_modules/nsfw/build/Release/nsfw.node',
            'node_modules/@theia/node-pty/build/Release/pty.node',
            'node_modules/fsevents/lib/binding/Release/**/*'
        ],
        verbose: true
    })

})()